# Generated by Django 5.2.7 on 2025-11-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock', 'stock'), ('caducidad', 'caducidad')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('criticidad', models.CharField(default='critico', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('resuelta', 'resuelta')], default='activa', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventory.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'estado'], name='inventory_a_tipo_198c38_idx'), models.Index(fields=['producto', 'tipo', 'estado'], name='inventory_a_product_73ddb0_idx')],
            },
        ),
    ]
