# Generated by Django 5.2.7 on 2025-11-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
