# Generated by Django 5.2.7 on 2025-11-07 04:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_venta_ventaitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='creada_por',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='anulada',
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventory.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
