# Generated by Django 5.2.7 on 2025-11-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_creada_por_venta_usuario_remove_venta_anulada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
