# Generated by Django 5.2.7 on 2025-11-07 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_venta_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
