# Generated by Django 5.2.7 on 2025-11-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
