# Generated by Django 5.2.7 on 2025-11-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_venta_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
