# Generated by Django 5.2.8 on 2025-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_venta_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='explicacion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
