# Generated by Django 5.1.2 on 2026-04-08 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_expand_movimiento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_mov',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
