# Generated by Django 5.1.15 on 2026-05-27 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_expand_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de ganancia (ej: 15 = 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio al que llega del laboratorio/proveedor', max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_mov',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
