# Generated by Django 5.1.15 on 2026-05-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_precio_costo_margen'),
        ('inventory', '0016_venta_motivo_anulacion'),
    ]

    operations = [
    ]
