# Generated by Django 5.1.15 on 2026-05-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_merge_20260527_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('vencido', 'vencido'), ('devolucion', 'devolucion')], db_index=True, default='activo', max_length=12),
        ),
    ]
