# Generated by Django 5.1.15 on 2026-05-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_estado_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='False = medicamento desactivado, conserva historial'),
        ),
    ]
